### ISSUE TITLE
aiml Kernel error

### ISSUE THREAD

**Issue by shravankumar147** [sohelamin/chatbot#6]
While running the main.py, it's throwing the following error.

> `AttributeError: module 'aiml' has no attribute 'Kernel'`

**Comment by lgming** [comment]
try to build using python2.7 but not python3.X

**Comment by logeshhy** [comment]
Has this resolved?

**Comment by pyaepyaelily** [comment]
is there a way to do it in python3.X?
